# Security Login
login:
    pattern:   /login
    defaults:  { _controller: BloggerBlogBundle:Security:login }
login_check:
    pattern:   /login_check
    defaults:  { _controller: BloggerBlogBundle:Security:logincheck }
logout:
    pattern:   /logout
    defaults:  { _controller: BloggerBlogBundle:Security:logout }

# BloggerBlogBundle
blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
