# Security Login
login:
    pattern:   /admin/login
    defaults:  { _controller: BloggerBlogBundle:Security:login }
login_check:
    pattern:   /admin/login_check
logout:
    pattern:   /admin/logout

# BloggerBlogBundle
blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
