jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Blogger\BlogBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: BloggerBlogBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        # NOTE: login_path, check_path and logout path must match the pattern of the firewall
        secured_area:
            pattern:    ^/admin/
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path:   /admin/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            
        #admin_area:
        #    pattern:    ^/admin
        #    http_basic: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/*, roles: ROLE_ADMIN }
        - { path: ^/admin/category/*, roles: ROLE_ADMIN }
        - { path: ^/admin/blog/delete/*, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }
