# page route
blogger_blog_page_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method: GET

blogger_blog_page_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method: GET
        
blogger_blog_page_contact:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method: GET|POST

blogger_blog_page_tag_search:
    pattern: /tag/{tag}
    defaults: { _controller: BloggerBlogBundle:Page:tagsearch }
    requirements:
        _method: GET

# blog route
blogger_blog_blog_show:
    pattern: /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method: GET
        id: \d+
        
blogger_blog_blog_create:
    pattern: /create
    defaults: { _controller: BloggerBlogBundle:Blog:create }
    requirements:
        _method: GET|POST

blogger_blog_blog_update:
    pattern: /update/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:update }
    requirements:
        _method: GET|POST
        id: \d+

# comment route
blogger_blog_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
